### ISSUE TITLE
Clean up the engine

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#100]
Just as the title says. We took the motor apart. The top of the block cracked at some point in it's life and someone just welded it back together, poorly. It's nowhere near flat and should be fixed. Good news, the pistons, cylinders, valves and crank are all really nice. I may remove the cam shaft.

## Tools
- [x] Head valve spring compressor
- [x] Block valve spring compressor
- [x] Cylinder ring compressor

## Parts
- [x] Order new piston rings
- [x] Order new valves springs
- [x] Order new old stock head bolts
- [x] Order a new copper head gasket
- [x] Order a new oil line to connect the block to the head
- [x] Order high heat resistant paint
- [x] Order new exhaust stud

## Todo
- [x] Remove the intake valves
- [x] Clean the intake valves
- [x] Replace the intake springs
- [x] Remove the exhaust valves
- [x] Clean the exhaust valves
- [x] Replace the exhaust springs
- [x] Remove the distributor
- [x] Take the head apart
- [x] Strip the paint from the block
- [x] Figure out what to do with the block
- [x] Clean the pistons and hardware
- [x] Remove old piston rings
- [x] Install new piston rings
- [x] Clean the top of the block
- [x] Strip the paint from the block
- [x] Paint the block
- [x] Remove the broken exhaust stud (replaces #74)
- [x] Install the water pump gasket
- [x] Install the fuel pump
- [x] Install the timing gear cover
- [x] Clean out the distributor hole
- [x] Clean the oil pan
- [x] Clean the oil pickup
- [x] Install the distributor

**Comment by zachseifts** [comment]
Ordered a ring compressor and valve tool this morning.

**Comment by zachseifts** [comment]
Pulled the distributor out last night and started working on cleaning up the head.

**Comment by zachseifts** [comment]
Ordered piston rings and valve springs from Rock Auto.

**Comment by zachseifts** [comment]
It's in paint stripper right now.

**Comment by zachseifts** [comment]
The piston rings and valve springs are in. We took the valves out of the head last Tuesday and they looked good.

**Comment by zachseifts** [comment]
I've also started working on the oil pan

**Comment by zachseifts** [comment]
Jason came over and we replaced the valve springs.

**Comment by zachseifts** [comment]
Just ordered new old stock head bolts from Kaiser Willys, going to order the head gasket and other accessories from Walck's in a few minutes.

**Comment by zachseifts** [comment]
Just ordered a head gasket

**Comment by zachseifts** [comment]
Started cleaning the oil pan and working on the broken exhaust stud.

**Comment by zachseifts** [comment]
Removed the broken exhaust stud, I need to get a helicoil kit for it.

**Comment by zachseifts** [comment]
Things are moving along quickly, we ground the block down, honed the cylinders, removed the old rings and started reinstalling the pistons. We broke the ring compressor, so I'm going to get another one from Napa tomorrow.

**Comment by zachseifts** [comment]
The pistons are back in the engine!

**Comment by zachseifts** [comment]
Fixed the broken exhaust stud, put the timing gears on and fixed the cam shaft.

**Comment by zachseifts** [comment]
Installed the water pump, timing gear cover and fuel pump.

**Comment by zachseifts** [comment]
![IMG_2882](https://user-images.githubusercontent.com/49168/57629671-2b014f00-756a-11e9-839e-f064c45b453a.JPG)
![IMG_2883](https://user-images.githubusercontent.com/49168/57629673-2d63a900-756a-11e9-8aef-4b87bb69fe7f.JPG)
![IMG_2886](https://user-images.githubusercontent.com/49168/57629694-38b6d480-756a-11e9-8943-0a4ae1b2e0c2.JPG)

**Comment by zachseifts** [comment]
Front pulley, oil pump and distributor are all installed.

**Comment by zachseifts** [comment]
Painted rear engine plate.

**Comment by zachseifts** [comment]
Everything is torqued and the oil pan is on.

**Comment by zachseifts** [comment]
Clutch is in and it is ready to be joined to the gears.
