### ISSUE TITLE
Rebuild the oil pump

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#102]
We should take a look at what the inside of the oil pump looks like. Also, it has a few gaskets that should be replaced.

### TODO

- [x] Take it apart
- [x] Clean the parts
- [x] Change bolts
- [x] Replace the gasket
- [x] Rebuild

### Parts

 * [Part name](link)

**Comment by zachseifts** [comment]
Cleaned it up and replaced the gaskets. It looks good inside.
