### ISSUE TITLE
Clean up the transmission

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#103]
Even though it's not getting rebuilt, the transmission needs to be cleaned up.

### TODO

- [x] Clean the case
- [ ] Paint everything
- [ ] Clean up the sifter assembly
- [ ] Paint things that should be painted

**Comment by zachseifts** [comment]
I've stripped the paint and it's ready to go back into the gear train.
