### ISSUE TITLE
Clean up the speedometer & install new gauges

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#104]
The speedometer needs to be cleaned up and we need new oil pressure, temperature and volt gauges.

## TODO

- [x] Take the speedometer apart
- [x] Clean the internals
- [x] Strip the paint on the case
- [x] Fix the gasket or replace with gasket maker
- [x] Clean the threads on the mounting bolts
- [x] Replace all of the bulbs in it
- [x] Repaint the case
- [x] Order new speedometer cable
- [x] Install the speedometer cable
- [x] Order new gauge kit
- [x] Install mounting bracket for the new gauge kit

## Parts

- [x] [Bosch SP0F000054 Style Line 2" Triple Gauge Kit](https://www.amazon.com/gp/product/B00UM9X63C)
- [x] [Bosch SP0F000012 Copper Tubing Installation Kit](https://www.amazon.com/gp/product/B00UZ9HC2U)
- [x] [Speedometer Cable With Housing 60"](https://walcks4wd.com/speedometer-cable-with-housing.html)

**Comment by zachseifts** [comment]
Took apart the speedometer the other day, I need to strip the paint and clean it up a bit more.

**Comment by zachseifts** [comment]
Most of it is painted, I managed to screw up the outer casing, but i'll redo it tomorrow.

**Comment by zachseifts** [comment]
Accidentally bought 2 speedometer cables, at least I'll have an extra.

**Comment by zachseifts** [comment]
The gauge mounting bracket is installed.

**Comment by zachseifts** [comment]
Done.
