### ISSUE TITLE
Put the gear assembly together

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#105]
The gear assembly for the jeep needs to be put together. It's getting closer.

## TODO

- [x] #86 Rebuild the transfer case
- [x] #103 Clean up the transmission
- [x] #97 Restore the parking brake
- [x] #87 Rebuild the pto selector
- [x] #77 Recondition the cross member and replace the mounts
- [x] #97 Restore the parking brake
- [x] Join the transmission to the transfer case
- [x] Join the transmission assembly to the bell housing
- [x] Clean up the transmission shifter assembly
- [x] Prime unpainted parts
- [x] Paint
- [x] Install the parking brake

**Comment by zachseifts** [comment]
The assembly was put together this weekend, is on a pallet waiting to be painted.

![IMG_2828](https://user-images.githubusercontent.com/49168/56132206-656dd100-5f57-11e9-921b-2036db55856d.JPG)

**Comment by zachseifts** [comment]
Primed and put on the first coat of paint.

**Comment by zachseifts** [comment]
Finished up the parking brake last night.

**Comment by zachseifts** [comment]
Everything is back together, ready to be installed.
