### ISSUE TITLE
Clean up the differentials

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#106]
The covers are off of the diffs and they need to be cleaned up.

## TODO

- [x] Drain and inspect the front differential
- [x] Clean front differential cover
- [x] Strip the paint from the front differential cover
- [x] Prime the front differential cover
- [x] Paint the front differential cover
- [x] Install new front differential cover seal
- [x] Install new front differential cover
- [x] Drain and inspect the rear differential
- [x] Clean rear differential cover
- [x] Add oil to the rear differential
- [x] Strip the paint from the rear differential cover
- [x] Prime the rear differential cover
- [x] Paint the rear differential cover
- [x] Install new rear differential cover seal
- [x] Install new rear differential cover
- [x] Clean out the front differential vent
- [x] Add oil to the front differential
- [x] Find and clean out the rear differential vent

## Parts

- [x] Differential oil

**Comment by zachseifts** [comment]
Covers are off and the gears look good.

**Comment by zachseifts** [comment]
Started to clean up the differential covers

**Comment by zachseifts** [comment]
Soaking the differential covers in simple green, going to strip paint and paint later.

**Comment by zachseifts** [comment]
Stripped the old paint and rust, started to paint the differential covers.

**Comment by zachseifts** [comment]
The rear differential is done and full of oil.

**Comment by zachseifts** [comment]
Took care of everything this morning, and it's not leaking.
