### ISSUE TITLE
Clean up the oil filter system

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#107]
The oil filter system needs to be cleaned up.

### TODO

- [x] Remove the filter assembly
- [x] Remove the filter
- [x] Clean up filter canister
- [x] Clean up mounting plate
- [x] Paint the mounting plate
- [x] Paint the oil filter canister mount
- [x] Paint the oil filter canister
- [x] Paint the oil filter canister lid

### Parts

- [x] [Oil filter](https://walcks4wd.com/oil-filter-element-c-4-large-l.html)
- [x] [Block to head oil line](https://walcks4wd.com/oil-line-block-to-head-f-head.html)
- [x] [90 degree fitting oil line to head](https://walcks4wd.com/90-degree-fitting-for-oil-line-to-head-all-f-head-4-cylinder.html)
- [x] [Straight oil line to head fitting](https://walcks4wd.com/straight-oil-line-to-head-fitting-f-head-4-cylinder-1950-1971.html)
- [x] [Oil filter out flex line](https://walcks4wd.com/oil-flex-line-filter-outlet-f.html)
- [x] [Oil filter in flex line](https://walcks4wd.com/oil-flex-line-oil-filter-inlet.html)

**Comment by zachseifts** [comment]
Ordered the parts from Walck's.

**Comment by zachseifts** [comment]
The oil filter canister is painted.

**Comment by zachseifts** [comment]
The oil filter system is installed.
