### ISSUE TITLE
Strip down the engine

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#110]
It's time to start rebuilding another engine. This one is stuck and I have no idea what it looks like inside.

## TODO

- [x] Get the engine out of the truck
- [x] Get the flywheel off
- [x] Mount it to the engine stand
- [x] Take it apart.
