### ISSUE TITLE
Combine both engines into a working one

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#111]
Both engines have useable parts and need to be combined to create one working engine.

## TODO

- [ ] Disassemble broken engine
- [ ] Check camshaft specs
- [ ] Build lower end
- [ ] Paint
- [ ] Assemble accessories

**Comment by zachseifts** [comment]
Used the cam, lifters, crank and rod bearings from the new engine. Used the pistons and rods from the old one.

**Comment by zachseifts** [comment]
The engine is painted.
