### ISSUE TITLE
Wire the head lights and tail lights

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#26]
I removed the headlight buckets and wiring while waiting on the paint to dry on the leaf springs. They're currently being stripped. I should paint them tomorrow and start on the wiring harnesses.

### Parts needed

 * Screws to hold it to the body
 * [Headlight junction block (3 post)](https://www.kaiserwillys.com/headlight-wire-junction-block-3-post-fits-41-71-jeep-willys) x2

### Todo

* [x] Wire the brake light switch to a relay
* [x] Headlight harness
* [x] Taillight harness
* [x] Mount the tail lights
* [x] Front LED lights
* [ ] Taillights and license plate light

**Comment by zachseifts** [comment]
- Purchased new plugs for the headlights
- Primed and painted the buckets and brackets

**Comment by zachseifts** [comment]
I'm going to run 3 circuits to front of the jeep:

 - headlights (along with tail lights)
 - running lights
 - accessory lights

**Comment by zachseifts** [comment]
Wiring harness is built and in place.

**Comment by zachseifts** [comment]
Installed the buckets and ran wires to the lights.

**Comment by zachseifts** [comment]
Turns out that my wiring harness wasn't long enough to reach the new location of the fuse box. I'll be rebuilding the harness this afternoon.

**Comment by zachseifts** [comment]
Combining this with the tail light wiring issue.

**Comment by zachseifts** [comment]
Running lights should be part of this issue too.

**Comment by zachseifts** [comment]
Wired in the fuel pump, ignition and ran a wire for the horn in the future. Also ran power and ground.

**Comment by zachseifts** [comment]
Ran the harness for the headlights and put together the plugs.

**Comment by zachseifts** [comment]
The headlights are in and they seem to work!

![img_2121](https://user-images.githubusercontent.com/49168/31613806-40a43688-b252-11e7-8ca9-ab943a1470b9.JPG)
![img_2124](https://user-images.githubusercontent.com/49168/31613812-44d9a274-b252-11e7-80f6-2a514b448168.JPG)

**Comment by zachseifts** [comment]
Removed the original rear wiring harness over the weekend and started to run the new harness to the rear of the jeep.

**Comment by zachseifts** [comment]
I'm going to change up the headlight harness and install a terminal strip to branch out the light circuits.

**Comment by zachseifts** [comment]
The brake light switch is now wired to a relay. Also, replacing the headlight splices with terminal blocks, they should be here next week.

**Comment by zachseifts** [comment]
Modified the terminal block and wired in the headlights to it. It works.

**Comment by zachseifts** [comment]
Built wiring harness for the rear lights.

**Comment by zachseifts** [comment]
Installed rear light harness and passenger side tail light.

**Comment by zachseifts** [comment]
Started wiring in the front LED lights.

**Comment by zachseifts** [comment]
Everything except for the ground is wired for the LED lights.

**Comment by zachseifts** [comment]
LED lights are grounded. Also cleaned up the grounds for the headlights.

**Comment by zachseifts** [comment]
This project depends on #9

**Comment by zachseifts** [comment]
Started running rear wiring harness and mounted the the terminal block for the rear lights.

**Comment by zachseifts** [comment]
Finished wiring in the tail lights this afternoon, everything works. Brake lights work too.

![img_2470](https://user-images.githubusercontent.com/49168/39555826-071a589a-4e4a-11e8-9e3d-6f2e9312e7d7.jpg)
