### ISSUE TITLE
Mount and wire switches in the dash

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#30]
We need a switch panel to mount switches to. 

### Related issues

- [x] #25 Add a fuse/relay box and add a wiring harness
- [x] #28 Wire the ignition system into the fuse/relay box
- [ ] #29 Wire the starting system into the fuse/relay box
- [ ] #26 Wire the head lights and tail lights
- [x] #23 Replace the running lights on the front of the jeep

**Comment by zachseifts** [comment]
Started building the face plate yesterday. Drilled, cut and painted the plate this morning.

**Comment by zachseifts** [comment]
Turns out the switch panel is not going to work. I'm going to drill some holes in the dash and mount some switches in there. It'll be a bit more water resistant.

**Comment by zachseifts** [comment]
Switches are wired and work.

![img_2136](https://user-images.githubusercontent.com/49168/31862499-f0be54d6-b70c-11e7-8097-5ef51890c055.JPG)
