### ISSUE TITLE
Mount the winch!

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#47]
Last weekend I took a trip to Tennessee and picked up a Warn HS9500I winch. It's a best and it needs to be mounted and wired in. Right now the exiting bull bar and other mounting brackets need to go.

![img_2459](https://user-images.githubusercontent.com/49168/39431025-7f9389ac-4c5d-11e8-8b55-775623db38bd.jpg)

### Todo:

- [ ] Remove the existing mounting bracket from the winch
- [ ] Remove bull bar and other old winch mounting parts
- [ ] Build and install a winch mount

**Comment by zachseifts** [comment]
I'm going in a different direction with the winch.
