### ISSUE TITLE
The brake lights are always on once the jeep runs for a while

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#50]
Once the jeep warms up and drives for a bit, the brake lights stay on. Something is wrong with the brake light switch. 

## Todo

- [x] Replace the brake light switch
- [x] Wire in the new switch

## Parts needed

- [x] Brake light switch

**Comment by zachseifts** [comment]
Changed the switch, this may help.
