### ISSUE TITLE
Rebuild the fuel system (again)

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#51]
The fuel system is garbage, the Solex carb is not putting out enough fuel to the motor and the fuel pump is putting out too much pressure. 

### Todo:

- [ ] Replace the Solex carb with the Carter YF
- [ ] Remove the fuel pressure regulator
- [ ] Install the mechanical fuel pump in after the electric (Using electric pump to prime the fuel mechanical pump)
- [ ] Plumb the fuel system.

### Parts needed

 * 90 degree fittings
 * fuel line
 * fuel fittings

**Comment by zachseifts** [comment]
The carter has been cleaned and rebuilt with the original gasket kit.
