### ISSUE TITLE
Replace the fuel system

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#52]
I'm going to fix the fuel system for real this time, the fuel line coming out of the bottom of the gas tank is kinked and leaking. The tank is empty, so is the carb and fuel system. It's time to simplify the setup.

So far, I have a Carter YF 938 SD carburetor and an AC 572 fuel pump. Both were purchased from Old Jeep Carbs, LLC. They are original equipment for the jeep.

The fuel line is going to be 1/4 inch rubber line. Already have fittings for the pump and the carb.

### Questions

 * Line positioning

### Todo

- [x] Remove the fuel tank and existing hard line.
- [x] Remove the fuel lines up to the carb.
- [x] Replace metal line from tank to fuel pump
- [x] Install fuel pump
- [x] Install carburetor
- [x] Plumb in system
- [x] Send warrantee info

**Comment by zachseifts** [comment]
Started to remove the fuel tank last week, the bolts are rusted in.

**Comment by zachseifts** [comment]
Took the gas tank out Saturday morning. Turns out it had gas in it and a lot of rust.

**Comment by zachseifts** [comment]
Purchased all of the parts I should need to install the tank. I need to look at lining the inside of the tank.

**Comment by zachseifts** [comment]
The tank is painted, cleaned and almost ready to go. The cap needs a gasket, but the old one might work. Ordered one from walck's 4 wheel drive this morning.

**Comment by zachseifts** [comment]
Tank is installed and new fuel line is ran. I ran the jeep on the old carb for a few minutes yesterday and moved it to it's new location.

**Comment by zachseifts** [comment]
Jeep is at the shop. Waiting on tools to finish removing the old Solex.

**Comment by zachseifts** [comment]
Last night I removed the old fuel pump, regulator, filter and valve setup and installed the Carter into the jeep.

**Comment by zachseifts** [comment]
The fuel pump is in and everything is plumbed in. Filters are between the tank and the fuel pump, and one between the fuel pump and the carb. I'll try starting it up tomorrow morning.

**Comment by zachseifts** [comment]
Everything is done, I need to send the warrantee info to Rick soon.
