### ISSUE TITLE
Rewire the jeep (again)

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#54]
I'd like to move the wiring out of the box under the passenger seat and into the engine compartment.

## TODO

- [x] Remove old wiring
- [x] Remove speedometer
- [x] Remove old light switch
- [x] Remove old key switch
- [x] Order 0/1 gauge wires for the battery cables, connectors and crimping tool
- [x] Order new battery connectors
- [x] Move power box, replays and junctions to a different location
- [x] Add starter switch
- [x] Change the connector on the switches from forks to ring connectors
- [x] Wire in switches
- [x] Make new battery cables
- [x] Make new ground cables
- [ ] Add Horn wiring & switch

**Comment by zachseifts** [comment]
Ordered parts on Amazon.

**Comment by zachseifts** [comment]
Started to move the wiring harness last night. Also removed the rest of the existing harness and speedometer.

**Comment by zachseifts** [comment]
Started work on the new harness and dealing with the placement of the components.

**Comment by zachseifts** [comment]
Ordered a bunch of parts from Amazon this morning, they should be here next week.

**Comment by zachseifts** [comment]
Started working on where to put all of the electrical components, I'm pretty sure everything will be under the cowl on the drivers side. The relays may be mounted elsewhere, I'm not sure yet.

**Comment by zachseifts** [comment]
Installed the fuse box, built new battery cables, started wiring switches in.

**Comment by zachseifts** [comment]
The coil, starter and gauges are wired in.

**Comment by zachseifts** [comment]
We're going to call this done for now.
