### ISSUE TITLE
Remove and bypass the heater

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#56]
The heater needs to be removed and the hose needs to be bypassed.

### TODO

- [x] Remove heater from cab
- [x] Remove heater controls from cab
- [x] Bypass the heater inlet and outlet.

**Comment by zachseifts** [comment]
Removed the heater, bypassed the removed heater and removed the controls for the heater.
