### ISSUE TITLE
The coolant needs to be changed

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#57]
Yesterday I removed all the coolant from the 3B and check out the thermostat. It made a huge mess.

### TODO

- [x] Cut a new gasket for the thermostat
- [x] Flush out the radiator
- [x] Trim the lower coolant return tube
- [x] Replace hose clamps
- [x] Replace the thermostat
- [x] Replace coolant

### Parts

 * thermostat
 * gasket paper
 * coolant

### Relates to

#15 Flush the coolant system

**Comment by zachseifts** [comment]
I have a 160° thermostat that I was going to use in the MB. It currently has a 180° thermostat in it.

**Comment by zachseifts** [comment]
Hooked everything back up Saturday afternoon, just need to put coolant in it and start the jeep.

**Comment by zachseifts** [comment]
Picked up some distilled water to mix with the coolant.

**Comment by zachseifts** [comment]
Coolant is in it and ran it for about 45 minutes.
