### ISSUE TITLE
Replace the temperature, oil pressure and voltage gauges

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#58]
Most of the gauges don't work on the jeep, they're going to be replaced.

### TODO

- [x] Remove old gauges
- [x] Install new ones
- [x] Run sensor wires and connections.

**Comment by zachseifts** [comment]
The bracket is in and the gauges are mostly mounted, waiting on running all of the other lines.

**Comment by zachseifts** [comment]
Done.
