### ISSUE TITLE
The transfer case doesn't work anymore

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#60]
So, the transfer case is really broken. Replaced the oil in the transmission and transfer case this afternoon and it still won't shift into neutral or low range. I'm pulling the engine Saturday.

### TODO

- [x] Drain the oil in the transfer case
- [x] Drain the oil in the transmission
- [x] Flush the transmission and transfer case
- [x] Replace the oil in the transfer case and transmission

### Parts

 * Mobil 1 Synthetic Gear Lube 75W-90
 * [Front differential gasket](https://www.amazon.com/gp/product/B008RAAOJW/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1)
 * [Rear differential gasket](https://www.amazon.com/gp/product/B008RAD3NG/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1)
