### ISSUE TITLE
Grease the front wheel bearings

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#61]
Like the rest of the jeep, the wheel bearing probably need some maintenance. 

## TODO

- [x] Remove front left locking hub
- [x] Remove front right locking hub
- [x] Remove the bearings
- [x] Clean the spindles
- [x] Clean the bearings
- [x] Replace all of the hub bolts
- [x] Repack front left wheel bearing
- [x] Repack front right wheel bearing
- [x] Clean up the front right locking hub
- [x] Clean up the right left locking hub

**Comment by zachseifts** [comment]
Took the bearings and hubs apart tonight, they're soaking in carb cleaner and will be repacked and installed tomorrow.

**Comment by zachseifts** [comment]
Bearings are packed and the hubs are back on the jeep. I need to clean up the locking hubs, make gaskets and repack the them.

**Comment by zachseifts** [comment]
I also purchased new bolts for the hubs today.

**Comment by zachseifts** [comment]
This has been done for a few weeks now.
