### ISSUE TITLE
Get ready to remove the engine

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#62]
The engine needs to come out on Saturday.

### TODO

- [ ] Remove the prop shafts
- [ ] Remove the pto shafts
- [ ] Drain and remove the fuel system
- [ ] Remove the wiring
- [ ] Remove the exhaust
- [ ] Remove the coolant
- [ ] Loosen the engine mounts
- [ ] Loosen transmission mounts
- [ ] Remove the gas pedal
- [ ] Remove the grill
- [ ] Remove the fenders
- [ ] Remove the radiator
- [ ] Remove the alternator
- [ ] Remove the fan

### Parts

 * Pretty much everything
