### ISSUE TITLE
Rebuild the prop shafts and replace u-joints

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#72]
The prop shafts need to be soaked in evaporust, painted and new u-joints need to be installed.

### TODO

- [x] Remove old u joints
- [x] Clean up the drive shafts and bolts
- [x] Prime the drive shafts and other parts
- [x] Paint the drive shafts
- [x] Replace the u-joints
- [x] Fix the grease zerks

### Parts

 * [ACDELCO 45U0107](https://www.rockauto.com/en/moreinfo.php?pk=356825&cc=1420614&jsn=1)

**Comment by zachseifts** [comment]
Ordered new u-joints from Rock Auto

**Comment by zachseifts** [comment]
Removed old u-joints and started to soak it in evaporust.

**Comment by zachseifts** [comment]
Checked on them yesterday, they are starting to clean up.

**Comment by zachseifts** [comment]
Started pulling the drive shafts apart. I can almost pull the front one apart.

**Comment by zachseifts** [comment]
Got the rear shaft apart, soaking in evaporust right now. Will paint tomorrow.

**Comment by zachseifts** [comment]
Primed the drive shafts this morning.

**Comment by zachseifts** [comment]
Started painting the drive shafts yesterday.

**Comment by zachseifts** [comment]
I need to buy more red paint.

**Comment by zachseifts** [comment]
The drive shafts are painted and ready to go.

**Comment by zachseifts** [comment]
The u-joints are in and everything is ready to go.
