### ISSUE TITLE
Rebuild the clutch linkage

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#73]
It's a mess and really rusty, it needs to be rebuilt.

### TODO

- [x] Remove from the frame
- [x] Clean with evaporust
- [x] Inspect bearing surfaces
- [x] Order rebuild kit
- [x] Build a new linkage arm

### Parts

 * Rebuild kit

**Comment by zachseifts** [comment]
Last week I ordered the parts I need for the clutch linkage. I also ordered some parts to replace the linkage arm with one with bearings.

**Comment by zachseifts** [comment]
New parts are in and I put together the new linkage bar.

**Comment by zachseifts** [comment]
Done.
