### ISSUE TITLE
Recondition the cross member and replace the mounts

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#77]
The mounts are all messed up and need to be replaced.

### TODO

- [x] Order new mounts
- [x] Clean up all of the pressing marks on the cross member
- [x] Paint the cross member
- [x] Restore the transmission to cross member mounting plate
- [x] Install new mounts on the cross member

### Parts

 * [ENGINE, TRANSMISSION & TRANSFER CASE MOUNT KIT (INSULATORS) FITS 41-71 JEEP WITH 4-134 ENGINE & DANA 18 TRANSFER CASE](https://www.kaiserwillys.com/engine-transmission-transfer-case-mount-kit-insulators-fits-41-71-jeep-with-4-134-engine-dana-18-transfer-case)

**Comment by zachseifts** [comment]
Ordered new ones from Kaiser Willys.

**Comment by zachseifts** [comment]
Received the new mounts.

**Comment by zachseifts** [comment]
Cleaned up the cross member over the weekend and started to paint it. It had a lot of manufacturing marks on it that are mostly gone now.

**Comment by zachseifts** [comment]
Painted the mounts and added another coat of paint to the cross member.

**Comment by zachseifts** [comment]
Added a few more coats of paint yesterday.

**Comment by zachseifts** [comment]
Installed the mounts and all that fun stuff.
