### ISSUE TITLE
The engine mounting plate is bent

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#78]
When the transmission cross member got bent, it looks like it bent the engine mounting plate too. It's pretty bad on the right side.

## Todo

- [x] Remove the pulley, timing gear cover, timing gears and everything else to get to the plate
- [x] Clean up the plate
- [x] Bend it back into shape
- [x] Paint it

**Comment by zachseifts** [comment]
It looks like [Willys Jeep Parts](https://www.willysjeepparts.com/Engine_Mounting.htm) has one for $110.00 649919

**Comment by zachseifts** [comment]
Removed it this morning and I'm about to start cleaning it up.

**Comment by zachseifts** [comment]
Used the press to straighten the left side of the mount, the right side isn't moving as much as it should.

**Comment by zachseifts** [comment]
I dropped it off at the machine shop this morning, they should be able to fix it.

**Comment by zachseifts** [comment]
It is painted and mounted to the block.
