### ISSUE TITLE
Replace the coolant and radiator hoses

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#83]
I have new radiator hoses for the jeep and it will need new coolant.

### TODO

- [x] Order new hoses
- [x] Remove old hoses
- [x] Drain coolant
- [x] Install new hoses
- [x] Refill coolant

### Parts

 * Upper and lower radiator hose
 * Coolant
 * New clamps

**Comment by zachseifts** [comment]
New hoses were ordered a while ago, closing this issue.
