### ISSUE TITLE
Rebuild the transfer case

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#86]
Got the transfer case open last night, it's pretty rusty inside.

![img_2780](https://user-images.githubusercontent.com/49168/53020126-4d307880-3424-11e9-9c87-5f238bff7ef8.JPG)
![img_2777](https://user-images.githubusercontent.com/49168/53020155-59b4d100-3424-11e9-82b8-e1e32070cee0.JPG)
![img_2779](https://user-images.githubusercontent.com/49168/53020166-5cafc180-3424-11e9-994b-7fe24609ce56.JPG)
![img_2782](https://user-images.githubusercontent.com/49168/53020182-63d6cf80-3424-11e9-9498-1b543ca870c4.JPG)

### TODO

- [x] Remove the shifter arms
- [x] Remove the pto
- [x] Take the transfer case off of the transmission
- [x] Take off the parking brake
- [x] Get the gears out
- [x] Order parts to rebuild
- [x] Get the broken bolt removed
- [x] Paint the bearing caps
- [x] Install seals and bearings on the caps
- [ ] Chase all of the holes in the case
- [x] Find new bolts for the case
- [ ] Reassemble

**Comment by zachseifts** [comment]
The transfer case has been split from the transmission. There's a lot of mess going on right here.

**Comment by zachseifts** [comment]
The brake is off of the transfer case, the front output nut is not coming off easily.

**Comment by zachseifts** [comment]
The bolt is on there. I may have to cut it off.

**Comment by zachseifts** [comment]
The transfer care is disassembled. The bearings are all awful and the gaskets are all shot. It needs a rebuild. The gears are soaking in degreaser right now and the case is in paint stripper.

**Comment by zachseifts** [comment]
The gears are mostly cleaned up and looking decent. I ordered the rebuild kit for the transfer case and a few other parts today.

**Comment by zachseifts** [comment]
Parts were shipped this morning, the case is still soaking in simple green. It looks okay.

**Comment by zachseifts** [comment]
Parts are here, I still need to work on getting the case cleaned up before putting it back together.

**Comment by zachseifts** [comment]
The case and other parts are clean and some of it is primed.

**Comment by zachseifts** [comment]
Dropped the case off at the machine shop to get the broken bolt removed.

**Comment by zachseifts** [comment]
The bolt is out of the case and I've started assembling the seals and bearings on the bearing caps.

**Comment by zachseifts** [comment]
Cleaned up the breather, it's ready to be painted.

**Comment by zachseifts** [comment]
Started putting everything together today. The gear selectors are in and working, I did leave out the interlock pill. The main shaft, gears and bearings are all in the case. I need to shim it and install the intermediate gear tomorrow.

**Comment by zachseifts** [comment]
The transfer case is done.

**Comment by zachseifts** [comment]
![IMG_2821](https://user-images.githubusercontent.com/49168/55957796-2973fc80-5c35-11e9-9f3d-6b1cdc933d86.JPG)
![IMG_2822](https://user-images.githubusercontent.com/49168/55957797-2aa52980-5c35-11e9-9122-91b22fd3e125.JPG)

**Comment by zachseifts** [comment]
![IMG_2825](https://user-images.githubusercontent.com/49168/56131778-6a7e5080-5f56-11e9-8d38-8d0e57e2c4b4.JPG)
![IMG_2828](https://user-images.githubusercontent.com/49168/56131779-6a7e5080-5f56-11e9-9e6a-80395ad8739d.JPG)
![IMG_2826](https://user-images.githubusercontent.com/49168/56131780-6a7e5080-5f56-11e9-8591-3500d59182ab.JPG)
![IMG_2827](https://user-images.githubusercontent.com/49168/56131781-6a7e5080-5f56-11e9-8777-2855883609b0.JPG)
