### ISSUE TITLE
Clean up the engine

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#90]
The engine should be cleaned, it's a bit of a mess.

### TODO

- [ ] Remove as much as I can
- [ ] Clean up the left side
- [ ] Clean up the right side

**Comment by zachseifts** [comment]
The engine is apart, so this will happen.
