### ISSUE TITLE
Remove the heater bypass hose

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#91]
It needs to go.

### TODO

- [x] Remove the hose
- [x] Remove the plug from the head
- [x] Plug the hole in the head
- [ ] Remove the plug from the water pump
- [ ] Plug the hole in the water pump

### Parts

 * [Part name](link)

**Comment by zachseifts** [comment]
I'm going to change the water pump, it will not have the ports for the heater in it.
