### ISSUE TITLE
Move the ignition coil to the body

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#94]
I broke a bolt in the block for the coil, I'm just going to move it to the firewall.

### TODO

- [x] Clean up the coil mount
- [ ] Paint the mount
- [ ] Install the mount
- [ ] Get a longer coil cable

**Comment by zachseifts** [comment]
The mount is soaking in evaporust.

**Comment by zachseifts** [comment]
Cleaned up the mount

**Comment by zachseifts** [comment]
Decided not to do this, the new block has the correct studs for the coil.
