### ISSUE TITLE
Restore the parking brake

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#97]
It's apart and the internals look like they're in decent condition.

## TODO

- [x] Inspect the shoes
- [x] Inspect springs
- [x] Figure out what the extra part is
- [x] Restore the adjuster
- [x] Restore the shoes
- [x] Clean the backing plate
- [x] Paint the backing plate
- [x] Clean the extra part
- [x] Paint the extra part
- [x] Clean the springs
- [x] Restore the assembly
- [x] Install new parts
- [x] Install brake drum

## Parts

- [x] [Emergency Brake Shoe Spring (Passenger Side One Hooked End) on Transfer Case Brake](https://walcks4wd.com/e-brake-top-shoe-spring-on-transfer-case.html)
- [x] [Emergency Brake Shoe Spring (Drivers Side With Hooked Ends) on Transfer Case Brake](https://walcks4wd.com/emergency-brake-lower-shoe-spring-on-transfer-case.html)
- [x] [Emergency Brake Retracting Spring CJ3B, CJ5, CJ6, Pick Up Truck, Station Wagon, Sedan Delivery, Jeepster](https://walcks4wd.com/emergency-brake-retracting-spring.html)

**Comment by zachseifts** [comment]
Primed the drum this morning

**Comment by zachseifts** [comment]
Started panting the drum, the adjuster looks like it may be good.

**Comment by zachseifts** [comment]
So, there's an extra part that I'm not sure where it went. It seems to be home made and may or may not be needed.

**Comment by zachseifts** [comment]
I figured out what the extra part is and started prepping it for paint.

**Comment by zachseifts** [comment]
Most of everything is painted and the springs are soaking in simple green. They should be finished tomorrow.

**Comment by zachseifts** [comment]
Started painting the backing plate.

**Comment by zachseifts** [comment]
I ordered new springs and a few other parts for this, reopening while I install the drum and other stuff.

**Comment by zachseifts** [comment]
Got all of the springs in the mail today, going to install tonight.

**Comment by zachseifts** [comment]
Everything is mounted on the transfer case.
