### ISSUE TITLE
The camshaft gear bolt is a mess

### ISSUE THREAD

**Issue by zachseifts** [zachseifts/jeeps#99]
The camshaft bolt seems to be too short and stripped. It needs to be replaced.

### TODO

- [x] Make sure the camshaft isn't broken
- [x] Fix the threads inside the camshaft
- [x] Replace the bolt and washer

**Comment by zachseifts** [comment]
It looks like the threads in the cam shaft are in decent shape. The old bolt was too short.

**Comment by zachseifts** [comment]
Helicoiled the gear and fixed it.
